### ISSUE TITLE
Issue with include_tasks and import_tasks 

### ISSUE THREAD

**Issue by JPinkney** [shaded-enmity/ansible-schema-generator#3] opened 2018-07-26 18:11 UTC
I'm not familiar with ansible but it seems include_tasks and import_tasks should be strings or objects instead of just objects.

_Related link: https://github.com/redhat-developer/vscode-yaml/issues/105_

**Comment by cmendible** [comment] 2018-09-03 23:01
Hi @shaded-enmity I can confirm this is an issue. When a module accepts free-form then the expected type should be a string.

**Comment by shaded-enmity** [comment] 2018-09-04 13:51
@JPinkney @cmendible Ahh, sorry for not responding sooner, for some reason I wasn't notified about the original issue.

I have a new version in brewing where this should be fixed, the problem is that the current code can handle only `free_form` command modules (`raw`, `shell`, `command`, `script`) while these "meta include/import" modules are something slightly different (and use `free-form`).

I should be able to get around to releasing a new schemas by Friday.

Thanks!

**Comment by shaded-enmity** [comment] 2018-09-07 18:13
Should be fixed in https://github.com/SchemaStore/schemastore/pull/543

**Comment by shaded-enmity** [comment] 2018-09-12 13:06
Closing the issue, if there are still problems with this please open a new one.

**Closed as completed by shaded-enmity** 2018-09-12 13:06 UTC
